### PR TITLE
Match media compat

### PR DESCRIPTION
**Pull request by muzam1l**

### CODE REVIEW

**Comment by 5471206srinivas** [comment]
Hello there are some bug in oning back camera and screen sharing in mobile
view so fix it

**Comment by muzam1l** [comment]
> Hello there are some bug in oning back camera and screen sharing in mobile view so fix it

Screen sharing is not available on mobile browsers and switching camera does not seem to be possible now as it is browsers who grants permission to single camera only.

Mobile devices hardly connect without TURN server, so that's not even the target of this project.

**Comment by 5471206srinivas** [comment]
If I converted website to app then it's possible

**Comment by muzam1l** [comment]
> If I converted website to app then it's possible

Well in native app you would get all necessary permissions , but then that would also require media server setup, as peer to peer to just useless there.

There is no point in porting this project to mobile as even its UI is not mobile friendly, even if you consider Webview/React Native

So you definitely have to start from scratch on mobile.

**Comment by muzam1l** [comment]
Please open a new issue, and post full details and screenshots if necessary, thanks

**Comment by 5471206srinivas** [comment]
Can give your whatsapp number number I will chat with you there

**Comment by 5471206srinivas** [comment]
My whatsapp number 9705647169

**Pull request closed without merging**
